# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  perform:
    strategy:
      matrix:
        repo_name:
          # define the list of repos here
          - codesnippet
          - colorbutton
          - fakeobjects
          - font
          - notification
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell        
      - name: prepare plugin
        run: |
          git clone https://github.com/ckeditor/ckeditor4.git ckeditor4
          git clone https://github.com/newren/git-filter-repo.git git-filter-repo
          cp -a git-filter-repo/git-filter-repo $(git --exec-path)
          ln -s $(git --exec-path)/git-filter-repo $(python -c "import site; print(site.getsitepackages()[-1])")/git_filter_repo.py
          echo "Processing ${{ matrix.repo_name }}"
          if [ ! -d ${{ matrix.repo_name }} ]; then
            mkdir -p ${{ matrix.repo_name }}
            pushd ${{ matrix.repo_name }} > /dev/null
            git init
            popd > /dev/null
          fi
          pushd ${{ matrix.repo_name }} > /dev/null
          git filter-repo --source ../ckeditor4 --preserve-commit-hashes --prune-empty always --subdirectory-filter plugins/${{ matrix.repo_name }}
          git checkout major
          for file in composer.json package.json
          do
            if [ ! -f ${file} ]; then
              sed -e "s/__PLUGIN__/${{ matrix.repo_name }}/g" ../skel/${file} > ${file}
              ../insert-beginning --file ${file}
            fi
          done
          git remote add origin git@github.com:drupal-ckeditor-libraries-group/${{ matrix.repo_name }}.git
          git branch --set-upstream-to=origin/major
          popd > /dev/null
